# Site settings
title: Welcome to my channel!
description: 'I am AYuan, An ordinary person who loves mathematics and computer science.'
url: 'https://ayuan-chan.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'AYuan'
  email: xsy20040408@outlook.com
  twitter_username: joshgerdes
  facebook_username: joshgerdes
  github_username:  joshgerdes
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

# kramdown 配置
kramdown:
  # 启用数学公式支持
  math_engine: mathjax
  # 允许解析 HTML 块
  parse_block_html: true
  # GitHub Flavored Markdown
  input: GFM
  # 语法高亮
  syntax_highlighter: rouge

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
